# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

multi-ecosystem-groups:
  all-updates:
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 1

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "all-updates"
  - package-ecosystem: "npm"
    directory: "/containers/ecr-viewer"
    patterns: ["*"]
    multi-ecosystem-group: "all-updates"
  - package-ecosystem: "docker"
    directory: "/containers/ecr-viewer"
    patterns: ["*"]
    multi-ecosystem-group: "all-updates"
  - package-ecosystem: "pip"
    directory: "/containers/orchestration"
    patterns: ["*"]
    multi-ecosystem-group: "all-updates"
  - package-ecosystem: "docker"
    directory: "/containers/orchestration"
    patterns: ["*"]
    multi-ecosystem-group: "all-updates"
  - package-ecosystem: "pip"
    directory: "/containers/fhir-converter"
    patterns: ["*"]
    multi-ecosystem-group: "all-updates"
  - package-ecosystem: "docker"
    directory: "/containers/fhir-converter"
    patterns: ["*"]
    multi-ecosystem-group: "all-updates"
  - package-ecosystem: "pip"
    directory: "/containers/ingestion"
    patterns: ["*"]
    multi-ecosystem-group: "all-updates"
  - package-ecosystem: "docker"
    directory: "/containers/ingestion"
    patterns: ["*"]
    multi-ecosystem-group: "all-updates"
  - package-ecosystem: "pip"
    directory: "/containers/message-parser"
    patterns: ["*"]
    multi-ecosystem-group: "all-updates"
  - package-ecosystem: "docker"
    directory: "/containers/message-parser"
    patterns: ["*"]
    multi-ecosystem-group: "all-updates"
  - package-ecosystem: "pip"
    directory: "/containers/trigger-code-reference"
    patterns: ["*"]
    multi-ecosystem-group: "all-updates"
  - package-ecosystem: "docker"
    directory: "/containers/trigger-code-reference"
    patterns: ["*"]
    multi-ecosystem-group: "all-updates"
  - package-ecosystem: "docker"
    directory: "/containers/fhir-converter-proxy"
    patterns: ["*"]
    multi-ecosystem-group: "all-updates"