services:
  locust:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./locustfile.py:/home/locust/locustfile.py
      - ./requirements.txt:/home/locust/requirements.txt
      - ./baseECR/star-wars:/home/locust/baseECR/star-wars
    command: >
      -f /home/locust/locustfile.py
      --web-host 0.0.0.0
      --host https://dev7.dibbs.cloud/ecr-viewer
    environment:
      - DUMMY_NBS_JWT=${DUMMY_NBS_JWT}
