services:
  postgres:
    extends:
      file: ../ecr-viewer/docker-compose.yaml
      service: postgres
    profiles: ["", "azure", "aws"]
  sqlserver:
    extends:
      file: ../ecr-viewer/docker-compose.yaml
      service: sqlserver
    profiles: ["sqlserver"]
  aws-storage:
    extends:
      file: ../ecr-viewer/docker-compose.yaml
      service: aws-storage
    profiles: ["aws"]
  azure-storage:
    extends:
      file: ../ecr-viewer/docker-compose.yaml
      service: azure-storage
    profiles: ["", "azure"]
  gcp-storage:
    extends:
      file: ../ecr-viewer/docker-compose.yaml
      service: gcp-storage
    profiles: ["gcp"]
  ecr-viewer:
    extends:
      file: ../ecr-viewer/docker-compose.yaml
      service: ecr-viewer
    profiles: ["", "azure", "aws", "sqlserver"]
    depends_on:
      azure-storage:
        condition: service_healthy
    environment:
      - CONFIG_NAME=AZURE_PG_DUAL
      - METADATA_DATABASE_SCHEMA=core
      - METADATA_DATABASE_MIGRATION_SECRET=test
      - |
        NBS_API_PUB_KEY=
        -----BEGIN PUBLIC KEY-----
        MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAnlA1YmmbydxQdBh7DAq0
        wUfsjR25eWZOB995mHclT3C46oLat3YLu70akLfoMXd9YcJe0d4q3sP7tS1J4QDO
        IkfapvK3ClDJR2VUERTzR9yQ+1B1Sd+MSful/V3aP9L6wPRAJmsmziizUBz+X0oN
        WTkGP/xi0F/IlyBfh2sk89JKKmgXSFbgDTD7+8L5WeRY5koR0KfDJLBcyerrcIPW
        1FyD8RbkUH78yJXc+/ThXKBNpsDTvV0k/4zqLSADIEmhQFkW8oYOfF4ufBGSnGdZ
        gPoWbKHtlK+m1sFWMq0hAtJsNKsJQocPAEO2NIxRCX4k6X9HfvCYVniDI4OdVz0V
        jTF+galQDAybgtYc9ZN8ROpePDVkCANHzniBJFOwzv2yekreqdX7M399uLB+ztDX
        Iz2RpZbGkgspl4TWvvB+eN64DJykmExImIw1nFc/6AVd3jhKSnCrckpGV3XaF8lW
        WMA6au0RXjmRa4YxO/uQbFZeFkM7aQtQK/CxqdBfG0SACcIMwU2S7Kb5+c9Hs687
        LI8j7j0oVyCiAyJ44Mi70i4A2GedyM6kzdixTmszin+c4tT8mYjmEMpJle6GLBIa
        aqEy3CVEqecFIo4ypfoo4GjTqvv/JjtxwBl1FPC+HzFkOjSoLbrDmn64NnQhXlC9
        kd+ONf43CmqDSTa3atSFq4sCAwEAAQ==
        -----END PUBLIC KEY-----
  orchestration-service:
    platform: linux/amd64
    build:
      context: .
    depends_on:
      fhir-converter-service:
        condition: service_started
      ingestion-service:
        condition: service_started
      trigger-code-reference-service:
        condition: service_started
      message-parser-service:
        condition: service_started
        required: false
      ecr-viewer:
        condition: service_started
    ports:
      - "${ORCHESTRATION_PORT_NUMBER}:8080"
    logging:
      driver: "json-file"
    env_file:
      - .env
    extra_hosts:
      - host.docker.internal:host-gateway
  fhir-converter-service:
    platform: linux/amd64
    build:
      context: ../fhir-converter
    ports:
      - "${FHIR_CONVERTER_PORT_NUMBER}:8080"
    logging:
      driver: "json-file"
  ingestion-service:
    platform: linux/amd64
    build:
      context: ../ingestion
    ports:
      - "${INGESTION_PORT_NUMBER}:8080"
    logging:
      driver: "json-file"
    environment:
      SMARTY_AUTH_ID: ${SMARTY_AUTH_ID}
      SMARTY_AUTH_TOKEN: ${SMARTY_AUTH_TOKEN}
  message-parser-service:
    platform: linux/amd64
    build:
      context: ../message-parser
    ports:
      - "${MESSAGE_PARSER_PORT_NUMBER}:8080"
    logging:
      driver: "json-file"
  trigger-code-reference-service:
    platform: linux/amd64
    build:
      context: ../trigger-code-reference
    ports:
      - "${TRIGGER_CODE_REFERENCE_PORT_NUMBER}:8080"
    logging:
      driver: "json-file"

volumes:
  db:
  azure-data:
  aws-data:
  gcp-data:
