apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecr-viewer.fullname" . }}-ingestion
  labels:
    {{- include "ecr-viewer.serviceLabels" . | nindent 4 }}
    app.kubernetes.io/component: ingestion
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ingestion.servicePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "ecr-viewer.name" . }}
    app.kubernetes.io/component: ingestion
