name: Test fhir-converter Container

on:
  # pull_request:
  #   branches:
  #     - "**"
  #   paths:
  #     - containers/fhir-converter/**
  # merge_group:
  #   types:
  #     - checks_requested
  push:
    branches:
      # - main
      - austin/update-fhir-converter
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TEST_RUNNER_DOTNET_VERSION: 8.0
  CONTAINER: fhir-converter

jobs:
  integration-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          repository: CDCgov/dibbs-FHIR-Converter
          # TODO: change this
          ref: boban/fhir-converter-api
      - name: Setup dotnet ${{env.TEST_RUNNER_DOTNET_VERSION}}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{env.TEST_RUNNER_DOTNET_VERSION}}
        run: dotnet test src/Dibbs.FhirConverterApi.FunctionalTests/Dibbs.FhirConverterApi.FunctionalTests.csproj
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ${{ env.CONTAINER }} Container
        uses: docker/build-push-action@v6
        with:
          context: ./containers/${{ env.CONTAINER }}
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
