name: Trigger dibbs-vm
run-name: "Trigger dibbs-vm: ${{ inputs.dibbs_service }}:${{ inputs.dibbs_version }} by @${{ github.actor }}"

on:
  workflow_dispatch:
    inputs:
      dibbs_service:
        type: choice
        description: "The service to build"
        required: true
        options:
          - dibbs-ecr-viewer
      dibbs_version:
        type: string
        description: "The version of dibbs-ecr-viewer to build"
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger dibbs-vm
        run: |
          repo_owner="CDCgov" 
          repo_name="dibbs-vm"  
          event_type="trigger-workflow" 
          service="${{ github.event.inputs.dibbs_service }}"
          version="${{ github.event.inputs.dibbs_version }}"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DIBBS_VM_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"service\": \"$service\", \"version\": \"$version\", \"unit\": false, \"integration\": true}}"
