name: Trigger Dev Deployment Workflow
run-name: "Trigger ${{ inputs.event_type }} on ${{ inputs.tf_branch }} - Container Tag: ${{ inputs.container_tag }}, Environment: ${{ inputs.environment }}, Terraform Branch: ${{ inputs.tf_branch }} by @${{ github.actor }}"

on:
  workflow_dispatch:
    inputs:
      container_tag:
        type: string
        description: "The container tag to deploy. Example: `5.0.0`"
        required: true
      tf_branch:
        type: string
        description: "The branch for Terraform checkout. Default is main."
        required: false
        default: main
      environment:
        type: choice
        options:
          - aws
          - azure
          - gcp
        description: "The service provider to deploy to."
        required: true
      event_type:
        type: choice
        options:
          - plans
          - deploys
        description: "The event type to trigger the workflow."
        required: true
  workflow_call:
    inputs:
      container_tag:
        type: string
        description: "The container tag to deploy. Example: `5.0.0`"
        required: true
      tf_branch:
        type: string
        description: "The branch for Terraform checkout. Default is main."
        required: false
        default: main
      environment:
        type: string
        description: 'The service provider to deploy to ("aws" or "azure").'
        required: true
      event_type:
        type: string
        description: "The event type to trigger the workflow."
        default: deploys

jobs:
  trigger_dev_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to ${{ inputs.environment }} Dev
        env:
          TF_BRANCH: ${{ inputs.tf_branch }}
          ENVIRONMENT: ${{ inputs.environment }}
          CONTAINER_TAG: ${{ inputs.container_tag }}
          EVENT_TYPE: ${{ inputs.event_type }}
        run: |
          service="dibbs-ecr-viewer"
          repo_owner="skylight-hq"
          repo_name="dibbs-tf-envs"
          tf_branch="$TF_BRANCH"
          event_type="trigger-dibbs-ecr-viewer-$ENVIRONMENT-dev-$EVENT_TYPE"
          container_tag="$CONTAINER_TAG"
          response="$(curl -L -w '%{http_code}\n' -o /dev/null \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DIBBS_SKYLIGHT_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"service\": \"$service\", \"version\": \"$container_tag\", \"tf_branch\": \"$tf_branch\"}}")"
          if [ $response -ne 204 ]; then
            echo "Failed to trigger the workflow."
            exit 1
          fi
          echo "View your workflow run at: https://github.com/skylight-hq/dibbs-tf-envs/actions"
          echo "Successfully triggered the workflow."
          echo "Service: $service"
          echo "Repository: $repo_owner/$repo_name"
          echo "Container Tag: $container_tag"
          echo "Terraform Branch: $tf_branch"
